
//! Autogenerated weights for `pallet_network`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2025-02-09, STEPS: `5`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Bob`, CPU: `11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --chain=dev
// --wasm-execution=compiled
// --pallet=pallet_network
// --extrinsic=*
// --steps=5
// --repeat=2
// --output=pallets/network/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_network`.
pub trait WeightInfo {
	fn do_deactivation_ledger() -> Weight;
}

/// Weights for `pallet_network` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Network::SubnetsData` (r:65 w:0)
	/// Proof: `Network::SubnetsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodeRegistrationEpochs` (r:1 w:0)
	/// Proof: `Network::SubnetNodeRegistrationEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxDeactivations` (r:1 w:0)
	/// Proof: `Network::MaxDeactivations` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::DeactivationLedger` (r:1 w:1)
	/// Proof: `Network::DeactivationLedger` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodesData` (r:32768 w:32768)
	/// Proof: `Network::SubnetNodesData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn do_deactivation_ledger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10211361`
		//  Estimated: `91313151`
		// Minimum execution time: 239_933_914_000 picoseconds.
		Weight::from_parts(245_118_444_000, 91313151)
			.saturating_add(T::DbWeight::get().reads(32836_u64))
			.saturating_add(T::DbWeight::get().writes(32769_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Network::SubnetsData` (r:65 w:0)
	/// Proof: `Network::SubnetsData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodeRegistrationEpochs` (r:1 w:0)
	/// Proof: `Network::SubnetNodeRegistrationEpochs` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::MaxDeactivations` (r:1 w:0)
	/// Proof: `Network::MaxDeactivations` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::DeactivationLedger` (r:1 w:1)
	/// Proof: `Network::DeactivationLedger` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Network::SubnetNodesData` (r:32768 w:32768)
	/// Proof: `Network::SubnetNodesData` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn do_deactivation_ledger() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `10211361`
		//  Estimated: `91313151`
		// Minimum execution time: 239_933_914_000 picoseconds.
		Weight::from_parts(245_118_444_000, 91313151)
			.saturating_add(RocksDbWeight::get().reads(32836_u64))
			.saturating_add(RocksDbWeight::get().writes(32769_u64))
	}
}